//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        public int FilmId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Year { get; set; }
        public string Director { get; set; }
        public byte[] Picture { get; set; }
        public string UserId { get; set; }
    }
}
